SELECT p.ID AS PROGECT_ID, TIMESTAMPDIFF(MONTH, p.START_DATE, p.FINISH_DATE) AS MONTH_COUNT
FROM project p
WHERE TIMESTAMPDIFF(MONTH, p.START_DATE, p.FINISH_DATE) IN (
    SELECT MAX(TIMESTAMPDIFF(MONTH, START_DATE, FINISH_DATE))
    FROM PROJECT);