CREATE TABLE IF NOT EXISTS worker(
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) >= 2 AND LENGTH(NAME) <= 1000),
    BIRTHDAY DATE CHECK (YEAR(BIRTHDAY)) >= 1900,
    LEVEL VARCHAR(255) NOT NULL CHECK (LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')),
    SALARY INT CHECK (SALARY >= 1000 AND  SALARY <= 100000));

CREATE TABLE IF NOT EXISTS client(
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(1000) CHECK (LENGTH(NAME) >= 1 AND LENGTH(NAME) <= 1000));

CREATE TABLE IF NOT EXISTS project(
    ID BIGINT PRIMARY KEY,
    CLIENT_ID BIGINT,
    START_DATE DATE,
    FINISH_DATE DATE,
    FOREIGN KEY (CLIENT_ID) REFERENCES client(ID));

CREATE TABLE IF NOT EXISTS project_worker(
    PROJECT_ID BIGINT,
    WORKER_ID BIGINT,
    PRIMARY KEY (WORKER_ID, PROJECT_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES project(ID),
    FOREIGN KEY (WORKER_ID) REFERENCES worker(ID));


